Create LICENSE.txt
Medha-B/unetdl4j pull request #19
Opened 2020-08-28 10:01 UTC by Medha-B

Apache License, version 2.0.

2020-08-29 15:16 UTC, kaitoii11 requested changes

2020-08-29 15:16 UTC, kaitoii11 commented on LICENSE.txt
> +   Copyright [yyyy] [name of copyright owner]
Add the year and owner here

2020-08-29 15:18 UTC, kaitoii11 commented
Add the License section in the README as well.

2020-08-29 15:44 UTC, Medha-B commented on LICENSE.txt
> +   Copyright [yyyy] [name of copyright owner]
Who is the owner though?

2020-08-29 15:55 UTC, kaitoii11 commented on LICENSE.txt
> +   Copyright [yyyy] [name of copyright owner]
I guess you can put the name for all 4 of us.

2020-08-29 19:26 UTC, merged

2020-08-30 12:24 UTC, kaitoii11 reviewed
LGTM